apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: atsep-role-binding
subjects:
- kind: Group
  name: keycloak:atsep
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: atsep-clusterrole
  apiGroup: rbac.authorization.k8s.io