kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami2
  labels:
    app: whoami2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami2
  template:
    metadata:
      labels:
        app: whoami2
    spec:
      containers:
        - name: whoami2
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami2
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: whoami2
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami2
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`whoami2.testwhoami.test`) && PathPrefix(`/notls`)
    middlewares:
      - name: testwhoami-oauth-redirect
    kind: Rule
    services:
    - name: whoami2
      port: 80
